[tool.poetry]
name = "aerometrics"
version = "0.1.0"
description = ""
authors = ["t.planes <thomas.planes@isae-supaero.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
